name: Build and Test Go Project
on:
  push
  pull_request
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Download dependencies
        run: go mod download

      - name: Run unit tests
        run: script/test

      - name: Build
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            go build -v -o github-mcp-server.exe ./cmd/github-mcp-server
          else
            go build -v -o github-mcp-server ./cmd/github-mcp-server
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-mcp-server-${{ runner.os }}
          path: |
            github-mcp-server*
